- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/ros.py
Save load maps blocks on hector slam startup
> Remove blocking code from saving and loading maps

- .github/workflows/python-package.yml
- install.sh
- src/stretch/version.py
Update version and remove a bad line that was added to install by accident
> Fix some issue in install + update version to 0.0.10

- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/modules/manip.py
- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/ros.py
- streaming works with gripper switch
> Bugfix: streaming support gripper broken

- README.md
- docs/learning_from_demonstration.md
> Update links to LeRobot in our code

- src/stretch/agent/zmq_client.py
- src/stretch/dynav/llm_localizer.py
- src/stretch/dynav/llm_server.py
- src/stretch/dynav/mapping_utils/__init__.py
- src/stretch/dynav/mapping_utils/a_star.py
- src/stretch/dynav/mapping_utils/voxel.py
- src/stretch/dynav/mapping_utils/voxel_map.py
- src/stretch/dynav/mapping_utils/voxelized_pcd.py
- src/stretch/dynav/ok_robot_hw/README.md
- src/stretch/dynav/ok_robot_hw/camera.py
- src/stretch/dynav/ok_robot_hw/image_publisher.py
- src/stretch/dynav/ok_robot_hw/robot.py
- src/stretch/dynav/ok_robot_hw/utils/grasper_utils.py
- src/stretch/dynav/robot_agent_manip_mdp.py
- src/stretch/dynav/run_manip.py
- src/stretch/dynav/run_ok_nav.py
- src/stretch/dynav/scannet.py
- src/stretch/dynav/voxel_map_localizer.py
- src/stretch/dynav/voxel_map_server.py
- src/stretch/motion/base/ik_solver_base.py
- src/stretch/motion/pinocchio_ik_solver.py
- src/stretch/requirements.txt
- src/stretch/visualization/rerun.py
> Dynamem merging

- docs/start_with_docker.md
Mdformat is failing - wants a newline
> Fix formatting in dcocker startup script

- .github/workflows/python-package.yml
- docker/Dockerfile.ros2
- src/stretch/version.py
This PR adds a clone and a colcon build step for a custom `slam_toolbox` repository to the robot Dockerfile.
> Add custom slam_toolbox to robot docker image

- .github/workflows/python-package.yml
- scripts/run_docker_gpu_machine.sh
- scripts/run_stretch_ai_ros2_bridge_server.sh
> Add `set -e` and extra output to docker startup scripts

- README.md
- docs/apps.md
> update apps documentation

- scripts/build-docker.sh
- scripts/build-robot-docker.sh
- scripts/run_docker_gpu_machine.sh
- scripts/run_stretch_ai_ros2_bridge_server.sh
> Update scripts to use python3 since it's available in default ubuntu environments and python is not

- scripts/run_docker_gpu_machine.sh
> Fix comment in docker file

- src/stretch/mapping/instance/instance_map.py
> Skip processing unviewable instances

- .github/workflows/docker.yml
> Create a workflow to automatically build images

- docker/Dockerfile.ros2
- src/stretch/version.py
- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/ros.py
- catch the case where wirst roll and pitch are not existing
- exploration tested on RE2 robots
> Support and docker images for RE2 robot

- docker/Dockerfile.ros2
- scripts/run_stretch_ai_gpu_client.sh
- scripts/run_stretch_ai_ros2_bridge_server.sh
- scripts/run_stretch_ai_ros2_bridge_server_no_d405.sh
- src/stretch/agent/base/managed_operation.py
- src/stretch/agent/operations/place_object.py
- src/stretch/agent/operations/rotate_in_place.py
- src/stretch/agent/operations/search_for_object.py
- src/stretch/agent/robot_agent.py
- src/stretch/agent/task/pickup/find_task.py
- src/stretch/agent/task/pickup/pick_task.py
- src/stretch/agent/task/pickup/pickup_executor.py
- src/stretch/agent/task/pickup/pickup_task.py
- src/stretch/agent/task/pickup/place_task.py
- src/stretch/app/ai_pickup.py
- src/stretch/config/default_planner.yaml
- src/stretch/core/task.py
- src/stretch/mapping/voxel/voxel.py
- src/stretch/perception/encoders/siglip_encoder.py
- src/stretch/version.py
- src/test/mapping/planner.yaml
- src/test/mapping/test_svm.py
> Atomic tasks in AI demo

- scripts/run_stretch_ai_gpu_client.sh
- scripts/run_stretch_ai_ros2_bridge_server.sh
- scripts/run_stretch_ai_ros2_bridge_server_no_d405.sh
- src/stretch/agent/task/pickup/find_task.py
switch to latest instead of version
> Update docker scripts to use latest version of image

- docs/start_with_docker.md
> add docker instructions for adding user to docker group

- docs/start_with_docker.md
Instruct users to restart docker after updating group permissions
> Instruct users to restart docker after updating group permissions

- src/stretch/core/task.py
> Fix issue where max failures was not set properly

- docs/start_with_docker.md
- src/stretch/agent/operations/grasp_object.py
- src/stretch/agent/robot_agent.py
- src/stretch/app/grasp_object.py
> changes for more fine-grained grasping

- src/stretch/agent/robot_agent.py
- src/stretch/app/mapping.py
- src/stretch/mapping/voxel/voxel.py
When you call start() in the agent, add allowed radius if > zero
> Add allowed radius to mapping code

- .pre-commit-config.yaml
> Disable mdformat so you can edit docs from Github

- README.md
- docker/Dockerfile.cuda-11.8
- docs/images/rerun_example.png
- src/stretch/agent/zmq_client.py
- src/stretch/utils/memory.py
- src/stretch/version.py
- src/stretch/visualization/rerun.py
adds x11 so you can run GUI apps in docker if need be
rerun app still does not work, so enable web browser support
> Add ui instructions for compatibility with Docker

- src/stretch/agent/robot_agent.py
- src/stretch/app/mapping.py
Adds sync audio calls in `RobotAgent::RunExploration` during initial mapping
> Add audio feedback in mapping

- src/stretch/version.py
> update docker version to 0.1.13

- src/stretch/app/ai_pickup.py
Disable realtime updates until we fix data access.
> Disable realtime flag in ai_pickup temporarily

- src/stretch/version.py
Update version number to 0.1.15
> update docker version to 0.1.15

- src/stretch/agent/robot_agent.py
- src/stretch/mapping/voxel/voxel.py
Remove some breakpoints that were added by accident
> Remove breakpoints

- docs/images/rerun_map.png
- docs/images/rerun_map_bad.png
- docs/install.md
- docs/llm_agent.md
- docs/start_with_docker_plus_virtenv.md
- install.sh
- src/stretch/agent/operations/grasp_object.py
- src/stretch/agent/robot_agent.py
- src/stretch/core/task.py
- src/stretch/mapping/voxel/voxel.py
- Adding binit's one change into the install script
- Use install script instead of duplicating instructions/install commands outside of it
- Testing with different cuda versions - add this as an argument so that the mamba environment is set up correctly
- add python -m in front of some pip commands for safety
> Update install script and instructions based on feedback from Charlie

- docs/llm_agent.md
- docs/start_with_docker_plus_virtenv.md
- src/stretch/app/chat.py
- src/stretch/audio/audio_recorder.py
- add `--talk` flag to the chat app
- fix issue with audio recording where first recording is bad
> Audio fixes and updates - improve voice chat experience

- docs/llm_agent.md
Clean up docs again.
From here: https://docs.google.com/document/d/1NOVbhkTutA-9k5uAt_cEMNfEdLRoo-l21lkUL5WBn-E/edit?tab=t.0
> Update llm doc to improve guidance

- src/stretch/config/example_cat_map.json
Add person to detic class list
> add person to detic cat map file

- src/stretch/app/view_images.py
- src/stretch/visualization/rerun.py
- sends rerun.Clear messages for big topics like point clouds
- does not do this for robot poses or goals
> Clear large things from rerun

- src/stretch/agent/operations/__init__.py
- src/stretch/agent/operations/extend_arm.py
- src/stretch/agent/operations/open_gripper.py
- src/stretch/agent/operations/rotate_in_place.py
- src/stretch/agent/operations/speak.py
- src/stretch/agent/operations/update.py
- src/stretch/agent/robot_agent.py
- src/stretch/agent/task/pickup/hand_over_task.py
- src/stretch/agent/task/pickup/pickup_executor.py
- src/stretch/agent/zmq_client.py
- src/stretch/app/hand_over_object.py
- src/stretch/llms/prompts/pickup_prompt.py
- src/stretch/mapping/instance/instance_map.py
*** WARNING: FOR THIS SIMPLE HANDOVER THE ROBOT HOLDS ITS ARM OUT WITHOUT CHECKING FOR POTENTIAL COLLISIONS. USE AT YOUR OWN RISK ***
This commit provides an example of adding a new task to stretch_ai that can be used with an LLM and speech recognition.
The example task is a simple form of handover that can hand an object to a person. The task first has the robot look around with its head tilted upward. While looking around the robot updates its map. Then, the robot queries the instances in its map to see if there is a person instance. If there is a person instance to which the robot can navigate, the robot navigates to the instance. If successful, the robot lifts its arm, extends its arm, opens its gripper, and retracts its arm. Throughout this process, the robot says what it is …
> handover example

- docs/dynamem.md
- src/stretch/agent/robot_agent_dynamem.py
- src/stretch/agent/task/dynamem/dynamem_task.py
- src/stretch/app/run_dynamem.py
- src/stretch/motion/algo/a_star.py
> Make Dynamem code work on Peiqi's side (and some docs update)

- docs/dynamem.md
- src/stretch/agent/robot_agent_dynamem.py
- src/stretch/agent/task/dynamem/dynamem_task.py
- src/stretch/app/run_dynamem.py
> Dynamem docs update

- docs/ovmm.md
This PR adds instructions on how to to the OVMM demo app.
> Add documentation for OVMM

- src/stretch/agent/operations/grasp_object.py
> A small change in codes that might help visual servo performance

- .github/workflows/python-package.yml
- src/stretch/agent/operations/grasp_object.py
- src/stretch/dynav/ok_robot_hw/dynamem_manipulation.py
- src/stretch/simulation/robocasa_gen.py
update verison to 0.2.0 in workflow
> Fix CI issues

- README.md
- docs/apps.md
- docs/images/PickPlaceFullTask.gif
- docs/images/RabbitChair.gif
- docs/images/VisualServoing.gif
- docs/images/orangecupinbox.gif
Replaced documentation gif files stored in repo that were causing LFS issue with smaller Github-hosted versions.
> Removed large gifs from repo

- src/stretch/agent/robot_agent.py
- src/stretch/app/ovmm.py
- make sure it enables realtime mode by force
- update docs to clarify some differences
- fix an issue in the logger where it would print out text-to-speech didnt load when it did
> Fixes for multi-step OVMM demo

- src/stretch/agent/operations/grasp_object.py
- src/stretch/app/grasp_object.py
Fix some issues that were preventing grasping from working on floor objects
> Fixes to grasping code

- src/stretch/agent/debug/dynamem_zmq_client.py
- src/stretch/agent/manipulation/dynamem_manipulation/dynamem_manipulation.py
- src/stretch/agent/manipulation/dynamem_manipulation/grasper_utils.py
- src/stretch/agent/robot_agent_dynamem.py
- src/stretch/agent/task/dynamem/dynamem_task.py
- src/stretch/agent/zmq_client.py
- src/stretch/app/run_dynamem.py
> Dynamem manipulation debug

- src/stretch/agent/task/dynamem/dynamem_task.py
Minor quality of life improvements for dynamem testing: text formatting and consistency with default option
> Minor quality of life improvements for dynamem testing: text formatting and consistency with default option

- src/stretch/agent/manipulation/dynamem_manipulation/dynamem_manipulation.py
- src/stretch/agent/manipulation/dynamem_manipulation/grasper_utils.py
- src/stretch/agent/zmq_client.py
- src/stretch/app/debug/dynamem_zmq_client.py
- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/api.py
- src/stretch_ros2_bridge/stretch_ros2_bridge/remote/server.py
Since there is latency in ros2 streaming and this latency makes calling head_to before arm_to impossible, I proposed this blocking PR.
However, this will the robot face some stopping so we should be cautious in using it. Request Chris' review.
> Some suggestion on blocking

- src/stretch/agent/operations/grasp_object.py
- src/stretch/agent/robot_agent.py
- src/stretch/agent/task/dynamem/dynamem_task.py
- src/stretch/agent/task/pickup/pickup_task.py
- src/stretch/config/default_planner.yaml
- src/stretch/perception/encoders/__init__.py
> Several suggestions on non-dynamem codes

- docs/discord_bot.md
- docs/images/discord0.png
- docs/images/dynamem_rerun.png
> Suggestions on Discord bot docs

- src/stretch/agent/operations/grasp_object.py
- src/stretch/app/grasp_object.py
Change timing configuration
Make it so grasp arm motions are blocking again, to avoid issues with network that cause it to oscillate
change grasp distance
> change timing settings and make grasp blocking

- docs/dynamem.md
- docs/simulation.md
- docs/start_with_docker_plus_virtenv.md
- src/stretch/version.py
Update version to 0.3.0 for merging devel into main. Fix minor issues in docs.
> Update version to 0.3.0

- src/setup.py
Just found the old installation file cannot be implemented successfully.
> installation update

- src/setup.py
- src/stretch/app/ovmm_lfd_demo.py
- src/stretch/llms/gemini_client.py
- src/stretch/llms/openai_client.py
- src/stretch/llms/qwen_client.py
- src/stretch/mapping/voxel/voxel_eqa.py
- src/stretch/mapping/voxel/voxel_map_dynamem.py
- src/stretch/mapping/voxel/voxel_map_eqa.py
- src/stretch/perception/captioners/example.jpg
- src/stretch/perception/captioners/openai_captioner.py
- src/stretch/perception/captioners/qwen_captioner.py
- src/stretch/version.py
> Hello peiqi/cleanup
